Bump okio from 3.11.0 to 3.16.0 (#124)
Bumps `okio` from 3.11.0 to 3.16.0.
Updates `com.squareup.okio:okio` from 3.11.0 to 3.16.0
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/square/okio/blob/master/CHANGELOG.md">com.squareup.okio:okio's
changelog</a>.</em></p>
<blockquote>
<h2>Version 3.16.0</h2>
<p><em>2025-07-29</em></p>
<ul>
<li>
<p>Fix: Change <code>Socket.asOkioSocket()</code> to resolve its source
<code>InputStream</code> and <code>OutputStream</code>
eagerly. This will throw a <code>SocketException</code> immediately if
the socket isn’t connected.
This behavior is consistent with our similar APIs,
<code>Socket.source()</code> and <code>Socket.sink()</code>.</p>
</li>
<li>
<p>Fix: Optimize <code>AsyncTimeout</code> on systems with a very large
number of active timeouts. This class
originally kept active timeouts in a linked list; with this update the
internal data structure is
a binary heap. The old runtime was 𝑂(𝑛²) to activate 𝑛 timeouts; with
this optimization the
runtime is 𝑂(𝑛 log 𝑛).</p>
</li>
<li>
<p>Upgrade: [Kotlin 2.2.0][kotlin_2_2_0].</p>
</li>
</ul>
<h2>Version 3.15.0</h2>
<p><em>2025-07-01</em></p>
<ul>
<li>
<p>Upgrade: [kotlinx-datetime
0.7.0-0.6.x-compat][datetime_0_7_0_compat]. The previous 3.14.0
release, <code>FakeFileSystem</code> broke binary-compatibility for
calls to <code>FakeFileSystem()</code>. This
restores that compatibility.</p>
</li>
<li>
<p>Breaking: Change <code>FakeFileSystem.clock</code> from a JVM field
to a property. This avoids a crash
running Okio in a Gradle 8.x plugin. This change is not
binary-compatible.</p>
</li>
</ul>
<h2>Version 3.14.0</h2>
<p><em>2025-06-28</em></p>
<ul>
<li>Upgrade: [kotlinx-datetime 0.7.0][datetime_0_7_0]. This impacts the
<code>okio-fakefilesystem</code>
artifact only. This is a binary-incompatible backwards-incompatible
change that cannot co-exist
with previous releases of <code>okio-fakefilesystem</code>! If you
observe a <code>NoSuchMethodError</code> calling
<code>FakeFileSystem.init</code>, update the calling code to this
release (or newer) and recompile. We don't
like imposing backwards-incompatible changes like this on you and do so
regretfully.</li>
</ul>
<h2>Version 3.13.0</h2>
<p><em>2025-06-13</em></p>
<ul>
<li>New: <code>okio.Socket</code> interface. This is a first step
towards low-level streaming networking support
for Kotlin/Multiplatform. This release provides two JVM-only
implementations: <code>asOkioSocket()</code>
adapts a <code>java.net.Socket</code> to our new interface, and
<code>inMemorySocketPair()</code> returns a pair of
mutually-connected sockets. We also anticipate that this interface will
be a useful abstraction
for proxies and tunnels.</li>
<li>New: In-development snapshots are now published to the [Central
Portal Snapshots repository].</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/square/okio/commit/8259b1dda3a6c9257f3e2fe30c3cbc1631135283"><code>8259b1d</code></a>
Prepare for release 3.16.0.</li>
<li><a
href="https://github.com/square/okio/commit/a0d0c5e56b7ad1c73e187d67cec9e8ecbc80a5c8"><code>a0d0c5e</code></a>
Upgrade to Kotlin 2.2.0 (<a
href="https://redirect.github.com/square/okio/issues/1670">#1670</a>)</li>
<li><a
href="https://github.com/square/okio/commit/9e25e039e3585e2417897681783b10670c6acf45"><code>9e25e03</code></a>
Get Socket.inputStream and outputStream eagerly (<a
href="https://redirect.github.com/square/okio/issues/1669">#1669</a>)</li>
<li><a
href="https://github.com/square/okio/commit/0e48b0de4180312268b72071cbd240e3cdd316c6"><code>0e48b0d</code></a>
Add heap implementation for AsyncTimeout (<a
href="https://redirect.github.com/square/okio/issues/1658">#1658</a>)</li>
<li><a
href="https://github.com/square/okio/commit/d9e59b6784d2a06f8456d00ff1f104dd4ad5efd2"><code>d9e59b6</code></a>
Update dependency com.diffplug.spotless:spotless-plugin-gradle to v7.2.1
(<a
href="https://redirect.github.com/square/okio/issues/1667">#1667</a>)</li>
<li><a
href="https://github.com/square/okio/commit/0cccd615821992706909c7a10883779ab2f7bedb"><code>0cccd61</code></a>
Update dependency com.diffplug.spotless:spotless-plugin-gradle to v7.2.0
(<a
href="https://redirect.github.com/square/okio/issues/1665">#1665</a>)</li>
<li><a
href="https://github.com/square/okio/commit/5355bcc7b0222c6633bd3ed89728b3f0c0449559"><code>5355bcc</code></a>
Update dependency com.vanniktech:gradle-maven-publish-plugin to v0.34.0
(<a
href="https://redirect.github.com/square/okio/issues/1659">#1659</a>)</li>
<li><a
href="https://github.com/square/okio/commit/4e88847967c5600461cad51a89927c5b74a4c648"><code>4e88847</code></a>
Update dependency com.google.jimfs:jimfs to v1.3.1 (<a
href="https://redirect.github.com/square/okio/issues/1657">#1657</a>)</li>
<li><a
href="https://github.com/square/okio/commit/7edbfd30044583506fe4b60cb0aa2ae111f8079d"><code>7edbfd3</code></a>
Update dependency com.android.tools.build:gradle to v8.11.1 (<a
href="https://redirect.github.com/square/okio/issues/1655">#1655</a>)</li>
<li><a
href="https://github.com/square/okio/commit/a96af6f226c8ef4e82a4d6235bb146e24bf37fff"><code>a96af6f</code></a>
Update dependency
org.jetbrains.kotlinx.binary-compatibility-validator:org.je...</li>
<li>Additional commits viewable in <a
href="https://github.com/square/okio/compare/parent-3.11.0...parent-3.16.0">compare
view</a></li>
</ul>
</details>
<br />

Updates `com.squareup.okio:okio-fakefilesystem` from 3.11.0 to 3.16.0
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/square/okio/blob/master/CHANGELOG.md">com.squareup.okio:okio-fakefilesystem's
changelog</a>.</em></p>
<blockquote>
<h2>Version 3.16.0</h2>
<p><em>2025-07-29</em></p>
<ul>
<li>
<p>Fix: Change <code>Socket.asOkioSocket()</code> to resolve its source
<code>InputStream</code> and <code>OutputStream</code>
eagerly. This will throw a <code>SocketException</code> immediately if
the socket isn’t connected.
This behavior is consistent with our similar APIs,
<code>Socket.source()</code> and <code>Socket.sink()</code>.</p>
</li>
<li>
<p>Fix: Optimize <code>AsyncTimeout</code> on systems with a very large
number of active timeouts. This class
originally kept active timeouts in a linked list; with this update the
internal data structure is
a binary heap. The old runtime was 𝑂(𝑛²) to activate 𝑛 timeouts; with
this optimization the
runtime is 𝑂(𝑛 log 𝑛).</p>
</li>
<li>
<p>Upgrade: [Kotlin 2.2.0][kotlin_2_2_0].</p>
</li>
</ul>
<h2>Version 3.15.0</h2>
<p><em>2025-07-01</em></p>
<ul>
<li>
<p>Upgrade: [kotlinx-datetime
0.7.0-0.6.x-compat][datetime_0_7_0_compat]. The previous 3.14.0
release, <code>FakeFileSystem</code> broke binary-compatibility for
calls to <code>FakeFileSystem()</code>. This
restores that compatibility.</p>
</li>
<li>
<p>Breaking: Change <code>FakeFileSystem.clock</code> from a JVM field
to a property. This avoids a crash
running Okio in a Gradle 8.x plugin. This change is not
binary-compatible.</p>
</li>
</ul>
<h2>Version 3.14.0</h2>
<p><em>2025-06-28</em></p>
<ul>
<li>Upgrade: [kotlinx-datetime 0.7.0][datetime_0_7_0]. This impacts the
<code>okio-fakefilesystem</code>
artifact only. This is a binary-incompatible backwards-incompatible
change that cannot co-exist
with previous releases of <code>okio-fakefilesystem</code>! If you
observe a <code>NoSuchMethodError</code> calling
<code>FakeFileSystem.init</code>, update the calling code to this
release (or newer) and recompile. We don't
like imposing backwards-incompatible changes like this on you and do so
regretfully.</li>
</ul>
<h2>Version 3.13.0</h2>
<p><em>2025-06-13</em></p>
<ul>
<li>New: <code>okio.Socket</code> interface. This is a first step
towards low-level streaming networking support
for Kotlin/Multiplatform. This release provides two JVM-only
implementations: <code>asOkioSocket()</code>
adapts a <code>java.net.Socket</code> to our new interface, and
<code>inMemorySocketPair()</code> returns a pair of
mutually-connected sockets. We also anticipate that this interface will
be a useful abstraction
for proxies and tunnels.</li>
<li>New: In-development snapshots are now published to the [Central
Portal Snapshots repository].</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/square/okio/commit/8259b1dda3a6c9257f3e2fe30c3cbc1631135283"><code>8259b1d</code></a>
Prepare for release 3.16.0.</li>
<li><a
href="https://github.com/square/okio/commit/a0d0c5e56b7ad1c73e187d67cec9e8ecbc80a5c8"><code>a0d0c5e</code></a>
Upgrade to Kotlin 2.2.0 (<a
href="https://redirect.github.com/square/okio/issues/1670">#1670</a>)</li>
<li><a
href="https://github.com/square/okio/commit/9e25e039e3585e2417897681783b10670c6acf45"><code>9e25e03</code></a>
Get Socket.inputStream and outputStream eagerly (<a
href="https://redirect.github.com/square/okio/issues/1669">#1669</a>)</li>
<li><a
href="https://github.com/square/okio/commit/0e48b0de4180312268b72071cbd240e3cdd316c6"><code>0e48b0d</code></a>
Add heap implementation for AsyncTimeout (<a
href="https://redirect.github.com/square/okio/issues/1658">#1658</a>)</li>
<li><a
href="https://github.com/square/okio/commit/d9e59b6784d2a06f8456d00ff1f104dd4ad5efd2"><code>d9e59b6</code></a>
Update dependency com.diffplug.spotless:spotless-plugin-gradle to v7.2.1
(<a
href="https://redirect.github.com/square/okio/issues/1667">#1667</a>)</li>
<li><a
href="https://github.com/square/okio/commit/0cccd615821992706909c7a10883779ab2f7bedb"><code>0cccd61</code></a>
Update dependency com.diffplug.spotless:spotless-plugin-gradle to v7.2.0
(<a
href="https://redirect.github.com/square/okio/issues/1665">#1665</a>)</li>
<li><a
href="https://github.com/square/okio/commit/5355bcc7b0222c6633bd3ed89728b3f0c0449559"><code>5355bcc</code></a>
Update dependency com.vanniktech:gradle-maven-publish-plugin to v0.34.0
(<a
href="https://redirect.github.com/square/okio/issues/1659">#1659</a>)</li>
<li><a
href="https://github.com/square/okio/commit/4e88847967c5600461cad51a89927c5b74a4c648"><code>4e88847</code></a>
Update dependency com.google.jimfs:jimfs to v1.3.1 (<a
href="https://redirect.github.com/square/okio/issues/1657">#1657</a>)</li>
<li><a
href="https://github.com/square/okio/commit/7edbfd30044583506fe4b60cb0aa2ae111f8079d"><code>7edbfd3</code></a>
Update dependency com.android.tools.build:gradle to v8.11.1 (<a
href="https://redirect.github.com/square/okio/issues/1655">#1655</a>)</li>
<li><a
href="https://github.com/square/okio/commit/a96af6f226c8ef4e82a4d6235bb146e24bf37fff"><code>a96af6f</code></a>
Update dependency
org.jetbrains.kotlinx.binary-compatibility-validator:org.je...</li>
<li>Additional commits viewable in <a
href="https://github.com/square/okio/compare/parent-3.11.0...parent-3.16.0">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>